global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'backend_metrics'
    static_configs:
      - targets: ['backend:8000']
        labels:
          group: 'backend_services'

  - job_name: 'frontend_metrics'
    static_configs:
      - targets: ['frontend:5173']  # Changed from 3000 to 5173
        labels:
          group: 'frontend_services'